allowBuilds:
  '@clerk/shared': set this to true or false
  esbuild: true
  msgpackr-extract: true
  msw: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
