/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiUploadthingSplatRouteImport } from './routes/api/uploadthing.$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as AdminDashboardUsersRouteImport } from './routes/_admin/dashboard.users'
import { Route as AdminDashboardCategoriesRouteImport } from './routes/_admin/dashboard.categories'
import { Route as AppCIdChar123SlugChar125RouteImport } from './routes/_app/c.$id.{-$slug}'
import { Route as AdminDashboardCoursesChar123IdChar125RouteImport } from './routes/_admin/dashboard.courses.{-$id}'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiUploadthingSplatRoute = ApiUploadthingSplatRouteImport.update({
  id: '/api/uploadthing/$',
  path: '/api/uploadthing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardUsersRoute = AdminDashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardCategoriesRoute =
  AdminDashboardCategoriesRouteImport.update({
    id: '/dashboard/categories',
    path: '/dashboard/categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AppCIdChar123SlugChar125Route =
  AppCIdChar123SlugChar125RouteImport.update({
    id: '/c/$id/{-$slug}',
    path: '/c/$id/{-$slug}',
    getParentRoute: () => AppRoute,
  } as any)
const AdminDashboardCoursesChar123IdChar125Route =
  AdminDashboardCoursesChar123IdChar125RouteImport.update({
    id: '/dashboard/courses/{-$id}',
    path: '/dashboard/courses/{-$id}',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/dashboard/courses/{-$id}': typeof AdminDashboardCoursesChar123IdChar125Route
  '/c/$id/{-$slug}': typeof AppCIdChar123SlugChar125Route
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/dashboard/courses/{-$id}': typeof AdminDashboardCoursesChar123IdChar125Route
  '/c/$id/{-$slug}': typeof AppCIdChar123SlugChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/_admin/dashboard/users': typeof AdminDashboardUsersRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/_admin/dashboard/courses/{-$id}': typeof AdminDashboardCoursesChar123IdChar125Route
  '/_app/c/$id/{-$slug}': typeof AppCIdChar123SlugChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/categories'
    | '/dashboard/users'
    | '/api/trpc/$'
    | '/api/uploadthing/$'
    | '/dashboard/courses/{-$id}'
    | '/c/$id/{-$slug}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/categories'
    | '/dashboard/users'
    | '/api/trpc/$'
    | '/api/uploadthing/$'
    | '/dashboard/courses/{-$id}'
    | '/c/$id/{-$slug}'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_admin/dashboard/categories'
    | '/_admin/dashboard/users'
    | '/api/trpc/$'
    | '/api/uploadthing/$'
    | '/_admin/dashboard/courses/{-$id}'
    | '/_app/c/$id/{-$slug}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiUploadthingSplatRoute: typeof ApiUploadthingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/uploadthing/$': {
      id: '/api/uploadthing/$'
      path: '/api/uploadthing/$'
      fullPath: '/api/uploadthing/$'
      preLoaderRoute: typeof ApiUploadthingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/users': {
      id: '/_admin/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AdminDashboardUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard/categories': {
      id: '/_admin/dashboard/categories'
      path: '/dashboard/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AdminDashboardCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/c/$id/{-$slug}': {
      id: '/_app/c/$id/{-$slug}'
      path: '/c/$id/{-$slug}'
      fullPath: '/c/$id/{-$slug}'
      preLoaderRoute: typeof AppCIdChar123SlugChar125RouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/dashboard/courses/{-$id}': {
      id: '/_admin/dashboard/courses/{-$id}'
      path: '/dashboard/courses/{-$id}'
      fullPath: '/dashboard/courses/{-$id}'
      preLoaderRoute: typeof AdminDashboardCoursesChar123IdChar125RouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardCategoriesRoute: typeof AdminDashboardCategoriesRoute
  AdminDashboardUsersRoute: typeof AdminDashboardUsersRoute
  AdminDashboardCoursesChar123IdChar125Route: typeof AdminDashboardCoursesChar123IdChar125Route
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardCategoriesRoute: AdminDashboardCategoriesRoute,
  AdminDashboardUsersRoute: AdminDashboardUsersRoute,
  AdminDashboardCoursesChar123IdChar125Route:
    AdminDashboardCoursesChar123IdChar125Route,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCIdChar123SlugChar125Route: typeof AppCIdChar123SlugChar125Route
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCIdChar123SlugChar125Route: AppCIdChar123SlugChar125Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiUploadthingSplatRoute: ApiUploadthingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
